# SPDX-FileCopyrightText: 2024, 2025 Scarlett Moore <sgmoore@kde.org>
#
# SPDX-License-Identifier: CC0-1.0
---
name: skanpage
confinement: strict
grade: stable
base: core24
adopt-info: skanpage
apps:
  skanpage:
    extensions:
      - kde-neon-6
    common-id: org.kde.skanpage.desktop
    desktop: usr/share/applications/org.kde.skanpage.desktop
    command: usr/bin/skanpage
    plugs:
      - audio-record
      - home
      - removable-media
      - avahi-observe
      - cups
      - raw-usb
      - hardware-observe
    environment:
      ALSA_CONFIG_PATH: "$SNAP/kf6/etc/asound.conf"
layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib
  /etc:
    bind: $SNAP/etc
  /usr/lib/sane:
    bind: $SNAP/usr/lib/sane
slots:
  session-dbus-interface:
    interface: dbus
    name: org.kde.skanpage
    bus: session
parts:
  # libsane:
  #   source: https://gitlab.com/sane-project/backends.git
  #   source-type: git
  #   source-tag: '1.2.1'
  #   source-depth: 1
  #   plugin: autotools
  #   autotools-configure-parameters:
  #     - --prefix=/usr
  #     - --sysconfdir=/etc
  #     - --with-avahi
  #   build-packages:
  #     # Everything of the build dependencies of the sane-backends
  #     # Debian package ...
  #     - libavahi-client-dev
  #     - libcups2-dev
  #     - libcurl4-gnutls-dev
  #     - libgphoto2-dev
  #     - libieee1284-3-dev
  #     - libjpeg-dev
  #     - libltdl3-dev
  #     - libpoppler-glib-dev
  #     - libsnmp-dev
  #     - libtiff-dev
  #     - libusb-1.0-0-dev
  #     - libxml2-dev
  #     - python3-minimal
  #     - autoconf-archive
  #     - rsync
  #   stage-packages:
  #     - libexif12
  #     - libgphoto2-6
  #     - libgphoto2-port12
  #     - libsnmp40
  #   organize:
  #     snap/skanpage/current/usr: usr
  #   override-build: |
  #     craftctl default
  #     rsync -a --ignore-existing $CRAFT_PART_INSTALL/ /
  libsane-airscan:
#    after: [libsane]
    source: https://github.com/alexpevzner/sane-airscan
    source-type: git
    source-tag: 0.99.27
    source-depth: 1
    plugin: make
    make-parameters:
      - prefix=/usr
      - sysconfdir=/etc
      - libdir=/usr/lib
    build-packages:
      # Everything of the build dependencies of the sane-airscan
      # Debian package ...
      - libavahi-client-dev
      - libavahi-common-dev
      - libjpeg-turbo8-dev
      - libpng-dev
      - libxml2-dev
      - libgnutls28-dev
      - libsane-dev
  ksanecore:
    after:
      # - libsane
      - libsane-airscan
    plugin: cmake
    source: https://invent.kde.org/libraries/ksanecore.git
    source-branch: master
    build-packages:
      - libsane-dev
    stage-packages:
      - libsane1
      - libsane-hpaio
      - libsane-common
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_TESTING=OFF
    build-environment: &build-environment
      - LD_LIBRARY_PATH: "$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$CRAFT_STAGE/usr/lib:$CRAFT_STAGE/lib:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:/snap/kf6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR"
      - PKG_CONFIG_PATH: "$CRAFT_STAGE/usr/lib/pkgconfig:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig:/snap/kf6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig"
  libksane:
    after:
      - ksanecore
    plugin: cmake
    source: https://invent.kde.org/graphics/libksane.git
    source-branch: master
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_TESTING=OFF
    build-environment: *build-environment
  kquickimageeditor:
    after:
      - libksane
    plugin: cmake
    source: https://invent.kde.org/libraries/kquickimageeditor.git
    source-branch: master
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_TESTING=OFF
    build-environment: *build-environment
  skanpage:
    after:
      - kquickimageeditor
    parse-info:
      - usr/share/metainfo/org.kde.skanpage.appdata.xml
    plugin: cmake
    source: .
    source-type: local
    build-packages:
      - libpng-dev
      - libtesseract-dev
      - libpulse0
    stage-packages:
      - libpulse0
      - libasound2
      - libasound2-plugins
      - libasound2-data
      - libtesseract5
      - tesseract-ocr-all
      - libieee1284-3t64
      - libpoppler-glib8t64
      - cups-client
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_TESTING=OFF
    build-environment: *build-environment
    prime:
      - -usr/lib/*/cmake/*
      - -usr/include/*
      - -usr/share/ECM/*
      - -usr/share/man/*
      - -usr/bin/X11
      - -usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0
      - -usr/lib/aspell/*
      - -usr/share/lintian
  cleanup:
    after:
      - skanpage
    plugin: nil
    build-snaps:
      - core24
      - kf6-core24
    override-prime: |
      set -eux
      for snap in "core24" "kf6-core24"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
      done
